title: Strony UW
description: Będzie łatwiej

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
show_downloads: false
theme: jekyll-theme-cayman
